### PR TITLE
Simplified geometry and removed white border

### PR DESCRIPTION
**Pull request by slightknack**
As per [the discord discussion](https://discordapp.com/channels/677929380315660288/677929380780965948/773593268880408596):

> So this is just a screenshot of the **new logo**, but I cleaned up all excess geometry and simplified the paths of the logo - the second image shows a pure vector inversion, highlighting that the white outline is no longer present.
>
> New Logo and Inverted Colors

Here's the **old logo** on a checkered background for comparison - note the white outline around the logo, and the hairline present on the door (because the door was made up of multiple pieces):

Old Logo Checkered Background

I might simplify things further, or recreate the logo from scratch to have a nicer construction.

---

~Before merge~ (nevermind, broken out to https://github.com/utah-rust/logo/issues/3):

- ~Once we have the final SVG shapes we want, ensure that the following are preserved (currently @ErichDonGubler is planning on doing this):~ 
    - [ ] ~XML header~
    - [ ] ~SVG version~
    - [ ] ~`id` and `class` attributes, inasmuch as it makes sense. If there's redesign work involved here, @ErichDonGubler is inclined to break that out into follow-up work.~

### CODE REVIEW

**Comment by ErichDonGubler** [comment]
I'm getting a 403 response code for the "old" link you have in OP -- is that on a private project, maybe?

**Comment by ErichDonGubler** [comment]
I don't have the time to actually try to reconcile them myself right this second (and I'm more than happy to, in case you're unsure), but I noticed that a there are a technically a few breakages between the old and new SVGs:

- [ ] The XML manifest at the top of the file (`<?xml version="1.0" encoding="UTF-8"?>`) is missing. Some applications might (unfortunately) depend on this.
- [ ] The SVG `version` attribute (`"1.1"`) is now missing -- it's okay if this changes, but specifying this is good practice, much for the same reason as the concern above.
- [ ] Several `id` and `class` attributes have also been removed. Is there a reason they might not apply anymore maybe? I'd prefer to afford web dev nerds (like myself) a way to configure styles with CSS after loading this SVG inline -- that was part of the original intent of the SVG, which in retrospect will be good to document in this file (and you don't need to handle here, if you don't want).

EDIT: The above checklist has been moved into OP.

**Comment by slightknack** [comment]
I tried to simplify the geometry of the logo manually by editing the file a
first, but once I was in knee-deep I realized there were a host of issues
with the file itself - unused paths, single shapes split into multiple
parts, inconsistent sizing, and so on. I understand the appeal of
manipulating images and vector graphics programmatically, but as a graphic
designer, I think when making non-trivial changes to a design file, it's
better to use a tool specifically designed for that job. Because of this, I
opted to import the svg into a design tool and clean up the file with the
more powerful abstractions afforded. As you can imagine, the svg was
regenerated when exported, which overwrote any previous metadata. I hope
that clarifies why the breaking changes were made.

Since that commit, I've made some more changes to the logo itself, which
I'm going to push soon. If you'd like to add in the manifest, version, and
label the ids and classes of various paths after I've done that, I'd very
much appreciate it. Thanks!

**Comment by ErichDonGubler** [comment]
@slightknack:

> I tried to simplify the geometry of the logo manually by editing the file a first, but once I was in knee-deep I realized there were a host of issues with the file itself - unused paths, single shapes split into multiple parts, inconsistent sizing, and so on. I understand the appeal of manipulating images and vector graphics programmatically, but as a graphic designer, I think when making non-trivial changes to a design file, it's better to use a tool specifically designed for that job. Because of this, I opted to import the svg into a design tool and clean up the file with the more powerful abstractions afforded. As you can imagine, the svg was regenerated when exported, which overwrote any previous metadata. I hope that clarifies why the breaking changes were made.

I definitely didn't expect you to make changes to this file by hand, and I recognize that most tools won't preserve this metadata. I should have acknowledged that earlier -- so, no worries there.

> f you'd like to add in the manifest, version, and
label the ids and classes of various paths after I've done that, I'd very
much appreciate it.

I do not mind doing this at all. :)

**Comment by ErichDonGubler** [comment]
@slightknack: I've moved the [metadata checklist](https://github.com/utah-rust/logo/pull/2#issuecomment-722047312) I made into the OP, just so it doesn't get lost (i.e., we have more discussion here).

**Comment by ErichDonGubler** [comment]
I think the momentum @coolaj86 is giving to this logo in our social media merits this getting merged, with my concerns just needing to be follow-up work. If this is already de-facto canonically used, might as well represent that.

Thanks for the awesome contribution, @slightknack. :)

**Comment by ErichDonGubler** [comment]
I've broken out the follow-up work for the SVG affordances I've complained about here to https://github.com/utah-rust/logo/issues/3. Merge time!

**Pull request merged**
